### ISSUE TITLE
`hsvaToRbga is not a function`

### ISSUE THREAD

**Issue by corysimmons** [bubble-dev/_#380]
![image](https://user-images.githubusercontent.com/224636/82506392-af67a580-9acd-11ea-88c3-f92b2dabfa50.png)

Build to commonjs please?

**Comment by xaviervia** [comment]
Hi @corysimmons, 

In retrospective I would have used named exports since they play nicer with a lot of editor features and work in both systems.

You can still use the `require()` notation as with any ESM optimized package, just add `.default` to it. The `main` build ([`node/index.js`](https://unpkg.com/browse/@fantasy-color/hsva-to-rgba@1.0.0/node/index.js)) is a CJS build so there should be no compatibility issue.

<img width="689" alt="Screen Shot 2020-05-21 at 15 51 41" src="https://user-images.githubusercontent.com/381614/82565869-679f5780-9b7b-11ea-8f99-aa95b2753835.png">

**Comment by corysimmons** [comment]
```js
.default
```
🤩 TIL. Thank you!
